install.packages("tidyverse")
install.packages("magrittr")

install.packages("httr")
install.packages("xml2")
install.packages("rvest")
install.packages("jsonlite")
install.packages("stringr")
install.packages("tm")
install.packages("rebus")
install.packages("tidytext")
install.packages("wordcloud")
install.packages("wordcloud2")
install.packages("RColorBrewer")
install.packages("ggthemes")

install.packages("plotrix")
install.packages("caret")
install.packages("car")
install.packages("reshape2")
install.packages("lubridate")
install.packages("randomForest")
install.packages("e1071")
install.packages("xgboost")
install.packages("caTools")
install.packages('gridExtra')
install.packages('corrplot')

install.packages("broom")
install.packages("scales")
install.packages("plyr")


library(Metrics)
library(pROC)
library(MASS)
library(GGally)
library(memisc)